CREATE TABLE outbox_messages
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    event_type   VARCHAR(255)                            NOT NULL,
    routing_key  VARCHAR(255)                            NOT NULL,
    payload      TEXT                                    NOT NULL,
    status       VARCHAR(255)                            NOT NULL DEFAULT 'PENDING',
    created_at   TIMESTAMP WITHOUT TIME ZONE             NOT NULL DEFAULT NOW(),
    published_at TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_outbox_messages PRIMARY KEY (id)
);

ALTER TABLE workstations
ALTER
COLUMN description TYPE VARCHAR(255) USING (description::VARCHAR(255));

ALTER TABLE roles
ALTER
COLUMN name TYPE VARCHAR(255) USING (name::VARCHAR(255));

ALTER TABLE reservations
ALTER
COLUMN status TYPE VARCHAR(255) USING (status::VARCHAR(255));

ALTER TABLE workstations
ALTER
COLUMN type TYPE VARCHAR(255) USING (type::VARCHAR(255));